"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$aws\
$gcloud\
$kubernetes\
$nats\
$golang\
$nodejs\
$python\
$rust\
$zig\
$mojo\
$git_branch\
$directory\
$line_break\
$character\
"""

[hostname]
ssh_only = false

[aws]
format = '[$symbol$profile]($style) '
symbol = '☁️ '

[gcloud]
format = '[$symbol$active]($style) '
disabled = false
symbol = '☁️ '

[kubernetes]
disabled = false

[nats]
disabled = false

[golang]
disabled = false

[nodejs]
disabled = false

[python]
python_binary = ["./.venv/bin/python", "python3", "python"]
disabled = false

[rust]
disabled = false

[zig]
disabled = false

[mojo]
disabled = false

